# Generated by Django 5.1.3 on 2024-11-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cpf',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='planos',
            field=models.CharField(choices=[('plano1', 'Plano 1'), ('plano2', 'Plano 2')], max_length=255, null=True),
        ),
    ]
