# Generated by Django 5.1.3 on 2024-11-22 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_userinfo_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_info',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_user_info', to='portal.userinfo'),
        ),
    ]
