# Generated by Django 5.1.3 on 2024-11-22 20:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_alter_customuser_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(db_column='user_email', on_delete=django.db.models.deletion.CASCADE, related_name='user_info_profile', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
