# Generated by Django 5.1.3 on 2024-11-25 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_dadosmatricula_user_info_alter_dadosmatricula_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
