# Generated by Django 5.1.3 on 2024-11-26 06:50

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0006_avaliacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avaliacao',
            name='data_horario',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
