from .userinfo_form import UserInfoCreationForm , UserInfoEditForm
from .customuser_forms import CustomUserCreationForm, CustomUserEditForm
from .matricula_forms import MatriculaCreationForm, MatriculaEditForm